### PR TITLE
Fix flushing logic and add functional test case.

### LINKED ISSUE #107: DB should not flush to closed segments
```
17:23:09.331474[I] creating database...
17:23:13.502315[I] starting HTTP server...
17:23:13.510196[I] http server: listening on 0.0.0.0:5678
18:35:40.229348[E] error when flushing data: namespace rtapi failed to flush data: shard 1 failed to flush data: segment writer is closed
shard 2 failed to flush data: segment writer is closed
shard 3 failed to flush data: segment writer is closed
shard 4 failed to flush data: segment writer is closed
shard 5 failed to flush data: segment writer is closed
shard 6 failed to flush data: segment writer is closed
shard 7 failed to flush data: segment writer is closed
18:36:40.229586[E] error when flushing data: namespace rtapi failed to flush data: shard 1 failed to flush data: segment writer is closed
shard 2 failed to flush data: segment writer is closed
shard 3 failed to flush data: segment writer is closed
shard 4 failed to flush data: segment writer is closed
shard 5 failed to flush data: segment writer is closed
shard 6 failed to flush data: segment writer is closed
shard 7 failed to flush data: segment writer is closed
18:37:40.229907[E] error when flushing data: namespace rtapi failed to flush data: shard 1 failed to flush data: segment writer is closed
shard 2 failed to flush data: segment writer is closed
shard 3 failed to flush data: segment writer is closed
shard 4 failed to flush data: segment writer is closed
shard 5 failed to flush data: segment writer is closed
shard 6 failed to flush data: segment writer is closed
shard 7 failed to flush data: segment writer is closed
```

### PR DESCRIPTION
**Pull request by notbdu**
Fixes #107 and #108. 

Also adds a functional test case that repros both issues.

### CODE REVIEW

File: persist/fs/writer.go [hunk 1]
```diff
@@ -27,18 +27,22 @@ var (
 
 // segmentWriter is responsible for writing segments to filesystem.
 type segmentWriter interface {
-	// Open opens the writer.
-	Open(opts writerOpenOptions) error
+	// Start persisting data to disk.
```
Comment (xichen2020) [inline persist/fs/writer.go]: nit: Should be a sentence, e.g., `Start starts persisting a segment`.

File: persist/fs/writer.go [hunk 2]
```diff
@@ -27,18 +27,22 @@ var (
...
+	Start(opts writerStartOptions) error
+
+	// Finish persisting data to disk.
```
Comment (xichen2020) [inline persist/fs/writer.go]: `Finish finishes persisting a segment and performs cleanups as necessary`.

File: storage/database.go [hunk 3]
```diff
@@ -250,6 +250,13 @@ func (d *db) Close() error {
 	d.state = databaseClosed
 
 	// Close database-level resources.
+	if err := d.mediator.Close(); err != nil {
+		return err
+	}
+
+	if err := d.Options().PersistManager().Close(); err != nil {
```
Comment (xichen2020) [inline storage/database.go]: This may need to wait till the current ticking finishes (which may perform a flush). Is that the case at the moment?

File: storage/flush_test.go [hunk 4]
```diff
@@ -0,0 +1,26 @@
+package storage
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestFlush(t *testing.T) {
```
Comment (xichen2020) [inline storage/flush_test.go]: Fine to leave this here for now, but this looks like an integration test rather than a unit test (which typically tests local functionalities than performing an end-to-end test).

File: storage/database.go (hunk 3 above)
Comment (xichen2020) [reply storage/database.go]: On a second thought this probably should just be removed, as closing the manager will cause the it to panic if it's in the middle of a flush, and all closing does is just setting some nil pointers (which doesn't matter much if the database is shutting down).

File: storage/flush_test.go (hunk 4 above)
Comment (notbdu) [reply storage/flush_test.go]: I put it here to access internal structs to force a flush.

File: storage/database.go (hunk 3 above)
Comment (notbdu) [reply storage/database.go]: Removing the close completely.
